# Travis CI (MIT License) configuration file for WP Starter Theme
# @link https://travis-ci.org/

# Declare project language.
# @link http://about.travis-ci.org/docs/user/languages/php/
language: php

# Specify when Travis should build.
branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache
    - ./vendor

# Git clone depth.
git:
  depth: 1

matrix:
  fast_finish: true

  include:
    - php: '5.6'
      env: WP_VERSION=latest PHP_LINT=1

    - php: '7.2'
      env: WP_VERSION=latest PHP_LINT=1
    - php: '7.2'
      env: WP_VERSION=trunk
    - php: '7.2'
      env: WP_VERSION=latest WP_PHPCS=1 WP_TRAVIS_OBJECT_CACHE=1

    - php: 'nightly'
      env: WP_VERSION=latest PHP_LINT=1

  allow_failures:
    - php: 'nightly'

# Prepare your build for testing.
# Failures in this section will result in build status 'errored'.
before_script:
  # Turn off Xdebug. See https://core.trac.wordpress.org/changeset/40138.
  - phpenv config-rm xdebug.ini || echo "Xdebug not available"

  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  # Couple the PHPUnit version to the PHP version.
  - |
    case "$TRAVIS_PHP_VERSION" in
    7.2|7.0|nightly)
      echo "Using PHPUnit 6.1"
      composer global require "phpunit/phpunit=6.1.*"
      ;;
    5.6)
      echo "Using PHPUnit 4.8"
      composer global require "phpunit/phpunit=4.8.*"
      ;;
    *)
      echo "No PHPUnit version handling for PHP version $TRAVIS_PHP_VERSION"
      exit 1
      ;;
    esac
  - og_dir="$(pwd)"
  - plugin_slug="$(basename $(pwd))"

  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      # Set up the WordPress installation.
      export WP_CORE_DIR=/tmp/wordpress/
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      echo "define( 'JETPACK_DEV_DEBUG', true );" >> $WP_CORE_DIR/wp-tests-config.php
      # Maybe install memcached.
      if [[ "$WP_TRAVIS_OBJECT_CACHE" == "1" ]]; then
        curl https://raw.githubusercontent.com/tollmanz/wordpress-pecl-memcached-object-cache/584392b56dc4adbe52bd2c7b86f875e23a3e5f75/object-cache.php > $WP_CORE_DIR/wp-content/object-cache.php
        echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
      fi
      # Set up the plugin. This assumes that this repo name matches the plugin name.
      mkdir -p "${WP_CORE_DIR}wp-content/plugins/$plugin_slug"
      cp -R . "${WP_CORE_DIR}wp-content/plugins/$plugin_slug/"
      # Hop into plugin's directory.
      cd ${WP_CORE_DIR}wp-content/plugins/$plugin_slug/
      # For debugging.
      which phpunit
      phpunit --version
    fi
  # Set up phpcs.
  - |
    if [[ "$WP_PHPCS" == "1" ]] ; then
      composer global require automattic/vipwpcs
      phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs,$HOME/.composer/vendor/automattic/vipwpcs
    fi
  - pwd

# Run test script commands.
# Default is specific to project language.
# All commands must exit with code 0 on success. Anything else is considered failure.
script:
  # Search for PHP syntax errors.
  #
  # Only need to run this once per PHP version.
  - |
    if [[ "$PHP_LINT" == "1" ]] ; then
      find . -type "f" -iname "*.php" -not -path "./vendor/*" | xargs -L "1" php -l
    fi
  # WordPress Coding Standards.
  #
  # These are the same across PHP and WordPress, so we need to run them only once.
  #
  # @link https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
  # @link http://pear.php.net/package/PHP_CodeSniffer/
  - |
    if [[ "$WP_PHPCS" == "1" ]] ; then
      phpcs -n
    fi
  # Run the theme's unit tests, both in single and multisite.
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      phpunit
      WP_MULTISITE=1 phpunit
    fi
# Receive notifications for build results.
# @link http://docs.travis-ci.com/user/notifications/#Email-notifications
notifications:
  email: false

# Xenial image has PHP versions 5.6,7.1,7.2 pre-installed
dist: xenial

# Xenial does not start mysql by default
services:
  - mysql
  - memcached
